name: Changelog

on:
  release:
    types: [released]

permissions: {}

jobs:
  changelog:
    name: Changelog
    permissions:
      contents: write
    uses: mozex/reusable-workflows/.github/workflows/changelog.yml@ab63849bd7154796870541e8bc7519905b95b73b # main
