name: Changelog

on:
  release:
    types: [released]

permissions: {}

jobs:
  changelog:
    name: Changelog
    permissions:
      contents: write
    uses: mozex/reusable-workflows/.github/workflows/changelog.yml@cdf79db7eab44bdc4af9a87d5e8f403b2334ffd3 # main
