name: Changelog

on:
  release:
    types: [released]

permissions: {}

jobs:
  changelog:
    name: Changelog
    permissions:
      contents: write
    uses: mozex/reusable-workflows/.github/workflows/changelog.yml@2b525367047b666e1fd22574e7916535089c3c2c # main
