name: Checks

on:
  push:
    branches: [main, '*.x']
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    uses: mozex/reusable-workflows/.github/workflows/code-styling.yml@2c29377e2b38ac9e913ca8308f84106986c9cc3c # main
    with:
      php_version: '8.5'
      test_mode: true

  types:
    name: Types
    uses: mozex/reusable-workflows/.github/workflows/code-analysis.yml@2c29377e2b38ac9e913ca8308f84106986c9cc3c # main
    with:
      php_version: '8.5'

  type-coverage:
    name: Type Coverage
    uses: mozex/reusable-workflows/.github/workflows/type-coverage.yml@2c29377e2b38ac9e913ca8308f84106986c9cc3c # main
    with:
      php_version: '8.5'
      phpunit_config_file: 'phpunit.xml.dist'
      min: 100

  tests:
    name: Tests P${{ matrix.php }} - L${{ matrix.laravel }} - Pest ${{ matrix.pest }} - ${{ matrix.dependency-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [11, 12, 13]
        pest: [3, 4]
        dependency-version: [prefer-lowest, prefer-stable]
        exclude:
          - php: 8.2
            pest: 4
          - laravel: '13'
            php: 8.2
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip
          coverage: none

      - name: Require dependencies
        run: composer require "pestphp/pest:^${{ matrix.pest }}" "laravel/framework:^${{ matrix.laravel }}" --no-interaction --no-update --with-all-dependencies

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress

      - name: Tests
        run: vendor/bin/pest --colors=always
